name: GymTrack React CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Check formatting
        run: yarn prettier
      - name: Run tests
        run: yarn test
      - name: Check lint
        run: yarn lint
      - name: Check build
        run: yarn build
